### ISSUE TITLE
g++-5, g++-4.8, clang++-3.7 failed to build on Ubuntu 14.06

### ISSUE THREAD

**Issue by 0xsuu** [Llama-Group/Project-Llama#124]
```
[ 40%] Building CXX object CMakeFiles/llama.dir/src/Utility/DataGenerator.cpp.o
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:26:90: error: specialization of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ in different namespace [-fpermissive]
 void llama::RandomData::generateRandomData<int>(std::vector<int> *targetVector, int count) {
                                                                                          ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:33:10: error:   from definition of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ [-fpermissive]
     void generateRandomData(std::vector<T> *targetVector, int count);
          ^
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:39:96: error: specialization of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ in different namespace [-fpermissive]
 void llama::RandomData::generateRandomData<double>(std::vector<double> *targetVector, int count) {
                                                                                                ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:33:10: error:   from definition of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ [-fpermissive]
     void generateRandomData(std::vector<T> *targetVector, int count);
          ^
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:52:106: error: specialization of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ in different namespace [-fpermissive]
 void llama::RandomData::generateRandomData<std::string>(std::vector<std::string> *targetVector, int count) {
                                                                                                          ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:33:10: error:   from definition of ‘template<class T> void llama::RandomData::generateRandomData(std::vector<_RealType>*, int)’ [-fpermissive]
     void generateRandomData(std::vector<T> *targetVector, int count);
          ^
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:74:112: error: specialization of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ in different namespace [-fpermissive]
 void llama::ContinuousData::generateContinuousData<int>(std::vector<int> *targetVector, int count, bool reverse) {
                                                                                                                ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:41:10: error:   from definition of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ [-fpermissive]
     void generateContinuousData(std::vector<T> *targetVector, int count, bool reverse);
          ^
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:81:118: error: specialization of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ in different namespace [-fpermissive]
 void llama::ContinuousData::generateContinuousData<double>(std::vector<double> *targetVector, int count, bool reverse) {
                                                                                                                      ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:41:10: error:   from definition of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ [-fpermissive]
     void generateContinuousData(std::vector<T> *targetVector, int count, bool reverse);
          ^
/home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:89:65: error: specialization of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ in different namespace [-fpermissive]
 (std::vector<std::string> *targetVector, int count, bool reverse) {
                                                                 ^
In file included from /home/hao/llama/Project-Llama/llama_cpp/src/Utility/DataGenerator.cpp:18:0:
/home/hao/llama/Project-Llama/llama_cpp/../llama_cpp/src/Utility/DataGenerator.h:41:10: error:   from definition of ‘template<class T> void llama::ContinuousData::generateContinuousData(std::vector<_RealType>*, int, bool)’ [-fpermissive]
     void generateContinuousData(std::vector<T> *targetVector, int count, bool reverse);
          ^
```

**Comment by 0xsuu** [comment]
Clang++ will do.
